### ISSUE TITLE
Name suggestion

### ISSUE THREAD

**Issue by pooya-mohammadi** [Zahra-Zamanshoar/gitignore_tutorial#1]
Hi dear Zahra
I think it's better to change the project's name to something like "gitignore_tutorial" or "gitignore_test" because having a project called `.gitignore` is really weird.
@Zzamani80

**Comment by Zahra-Zamanshoar** [comment]
Hi, 
dear Pooya
Thank you for your suggestion
This project is made as an experiment, of course, according to your precious evaluation, care must be taken in choosing its name, it will definitely be worked on.
